// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpacvyuocgfxkckguywu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwYWN2eXVvY2dmeGtja2d1eXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODQ4MzAsImV4cCI6MjA2NTQ2MDgzMH0.jKPQe03fkmspvK8KMcNVEsN0aJQYuPkFGiAex-Bn1lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);